# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Dervean's blog
paginate:       5
baseurl:        ""
url:            "https://dervean.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Dervean
  url:          https://github.com/Dervean
  email:        derveanme@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/Dervean/dervean.github.io

# Gems
gems:
  - jekyll-paginate
